MODULES = jailed
include $(THEOS)/makefiles/common.mk

ARCHS = armv7 arm64 arm64e

TWEAK_NAME = FrenchPropertyMagazineJailed
DISPLAY_NAME = French Property Magazine
BUNDLE_ID = com.kasiim.frenchpropertymagazine-jailed

FrenchPropertyMagazineJailed_FILES = Tweak.xm
FrenchPropertyMagazineJailed_IPA = 

include $(THEOS_MAKE_PATH)/tweak.mk
