MODULES = jailed
include $(THEOS)/makefiles/common.mk

ARCHS = armv7 arm64 arm64e

TWEAK_NAME = YablaJailed
DISPLAY_NAME = Yabla-Jailed
BUNDLE_ID = com.kasiim.yabla-jailed

YablaJailed_FILES = Tweak.xm
YablaJailed_IPA = 

include $(THEOS_MAKE_PATH)/tweak.mk
