MODULES = jailed
include $(THEOS)/makefiles/common.mk

ARCHS = armv7 arm64 arm64e

TWEAK_NAME = LivingFranceMagazine
DISPLAY_NAME = Living France Magazine
BUNDLE_ID = com.kasiim.livingfrancemagazine-jailed

LivingFranceMagazine_FILES = Tweak.xm
LivingFranceMagazine_IPA = 

include $(THEOS_MAKE_PATH)/tweak.mk
