MODULES = jailed
include $(THEOS)/makefiles/common.mk

ARCHS = armv7 arm64 arm64e

TWEAK_NAME = FranceMagazineJailed
DISPLAY_NAME = France Magazine
BUNDLE_ID = com.kasiim.francemagazine-jailed

FranceMagazineJailed_FILES = Tweak.xm
FranceMagazineJailed_IPA = 

include $(THEOS_MAKE_PATH)/tweak.mk
